title: My Github Page
author: mkvph0ch
email: --private--
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  The World of mkvph0ch

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
